title: SBP Software Core
description: >-
  An aggregated view Sanford Burnham Prebys Discovery Institutes computational contributions to science.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false

header_pages:
  - index.md
  - repos.md
